### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by RaviKumarK25** [thenifemi/PetShop#3]
Hi, i am trying your code, i am successfully run your code but product list is empty so please share database details.

**Comment by thenifemi** [comment]
Hey, I just checked and everything seems to be working fine, I'm sorry I
won't be able to share database information

**Comment by thenifemi** [comment]
@RaviKumarK25 Please Let me know if you were able to solve the issue.

**Comment by RaviKumarK25** [comment]
Hi, product list is empty so can you tell me product table structure? I want only Product Table.

**Comment by thenifemi** [comment]
@RaviKumarK25 hi, Everything is in the code. Please can you paste the exact error you are getting?

**Comment by RaviKumarK25** [comment]
Hi, i am not getting any error. Pet product details are empty! you have mentioned that "Fetched store images from Amazon" so i want Table details for this.

**Comment by thenifemi** [comment]
@RaviKumarK25 Pet products are stored in the firebase cloud firestore, the database structure can be found in the model folder, Or please elaborate exactly what you need... Maybe I'm not getting you nicely. thanks

**Comment by RaviKumarK25** [comment]
I am not found pet products in firebase cloud firestore! and i have successfully connected Firebase. Please send me your email id i will send you snapshots

**Comment by thenifemi** [comment]
@RaviKumarK25 thenifemi@gmail.com

**Comment by RaviKumarK25** [comment]
Thank you

**Comment by thenifemi** [comment]
I believe this issue has been solved, I will close it now. Thanks.

**Comment by RaviKumarK25** [comment]
Ok thank you.
