### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by vipuluthaiah** [thenifemi/PetShop#6]
I want to work..on fetching the json from online...how can i do this??

**Comment by thenifemi** [comment]
Online from where? sorry I don't understand your question

**Comment by thenifemi** [comment]
Hi @vipuluthaiah, have you ever worked with JSON APIs?

**Comment by vipuluthaiah** [comment]
the process of updating the products..in u r app is lil hard..Is there a better way to update the products???

**Comment by vipuluthaiah** [comment]
i successfully imported all the json to firebase
![image](https://user-images.githubusercontent.com/45168922/99894585-514d9200-2cab-11eb-804c-b04ff91f9c05.png)
![image](https://user-images.githubusercontent.com/45168922/99894593-5c082700-2cab-11eb-8022-cb1b98ca0093.png)

**Comment by vipuluthaiah** [comment]
The credentials.dart file is intentionaly not included. Create your own credentials file with your own API Keys.

i am confused here..Which api we need to add?? here

**Comment by vipuluthaiah** [comment]
![image](https://user-images.githubusercontent.com/45168922/99895103-5f041700-2cad-11eb-983f-75c31942e0c6.png)

**Comment by thenifemi** [comment]
You need to add your own Google Places API key, your own storage bucket link.

**Comment by vipuluthaiah** [comment]
it would b really great it you show u r code..u can blur the api keys ...i want wanna the var names ..

**Comment by vipuluthaiah** [comment]
p.s it would b great if u guide me which features i should work

**Comment by thenifemi** [comment]
const PLACES_API_KEY = 'your_own_google_places_api_key';
const FIREBASE_STORAGE_BUCKET = 'your_own_firebase_ storage_location_key';

You could try working on the search feature.

**Comment by vipuluthaiah** [comment]
FIREBASE CONNECTED BUT NOT ABLE TO LOAD PRODUCTS

**Comment by vipuluthaiah** [comment]
![aa12](https://user-images.githubusercontent.com/45168922/99950542-aa4c2180-2da2-11eb-91a2-b4e840ecdf2a.png)

**Comment by vipuluthaiah** [comment]
![image](https://user-images.githubusercontent.com/45168922/99950572-b6d07a00-2da2-11eb-8621-507287d0ff4d.png)

**Comment by vipuluthaiah** [comment]
IT WAS GIVING ME ERROR
![image](https://user-images.githubusercontent.com/45168922/99950683-eda69000-2da2-11eb-917d-19692c12116e.png)
so

![image](https://user-images.githubusercontent.com/45168922/99950734-0151f680-2da3-11eb-8e71-8882c13c68cf.png)

**Comment by vipuluthaiah** [comment]
i am still confused about the 
const FIREBASE_STORAGE_BUCKET = 'your_own_firebase_ storage_location_key';
i used this url
![image](https://user-images.githubusercontent.com/45168922/99950883-4413ce80-2da3-11eb-9543-cc5cb71abbad.png)

**Comment by vipuluthaiah** [comment]
FOR PLACES I USED THIS
![as323](https://user-images.githubusercontent.com/45168922/99951258-ca301500-2da3-11eb-9aa7-f83c867ba94d.png)

**Comment by vipuluthaiah** [comment]
if i am missing out ..help me out:D

**Comment by thenifemi** [comment]
Did you add your google-services.json file to the project?

**Comment by vipuluthaiah** [comment]
yesss 
it is connected to firebase

**Comment by vipuluthaiah** [comment]
i am stilll not clear about the which link u r talking about
const FIREBASE_STORAGE_BUCKET = 'your_own_firebase_ storage_location_key';
 FIREBASE_STORAGE_BUCKET url?

**Comment by vipuluthaiah** [comment]
![image](https://user-images.githubusercontent.com/45168922/99970176-7df3cd80-2dc1-11eb-9298-f62162ed7380.png)
this url right??

**Comment by vipuluthaiah** [comment]
firebase is connected
![image](https://user-images.githubusercontent.com/45168922/99970285-9c59c900-2dc1-11eb-96aa-fdae64d06148.png)

**Comment by vipuluthaiah** [comment]
![Uploading image.png…]()

**Comment by vipuluthaiah** [comment]
![image](https://user-images.githubusercontent.com/45168922/99972985-4424c600-2dc5-11eb-9e2d-4faee7abd1b9.png)
i have the products

**Comment by thenifemi** [comment]
I think I understand now. The images for the products are stored in my firebase storage bucket. you need to add your own images to your bucket, then add the links to the products in firestore.

**Comment by vipuluthaiah** [comment]
u want to say to add images to
Storage rather den cloud firestore??

**Comment by vipuluthaiah** [comment]
should i do this manually or we have a script to do that?

**Comment by vipuluthaiah** [comment]
![adwAwD13](https://user-images.githubusercontent.com/45168922/99984096-aa641580-2dd2-11eb-9778-ae4753e9a927.png)
should i add images to realtime database or Storage??

**Comment by thenifemi** [comment]
I did everything manually actually. The actual images go in the Storage Bucket and the link to the Images go in Cloud Firestore

**Comment by vipuluthaiah** [comment]
got it
is there any other easy way to do it?

**Comment by thenifemi** [comment]
I am not sure. Maybe using an external API

**Comment by vipuluthaiah** [comment]
i am still confued which u r i should pass in the code?
![232442](https://user-images.githubusercontent.com/45168922/99991681-5c074480-2ddb-11eb-8b31-7c1a54d71aaf.png)
![image](https://user-images.githubusercontent.com/45168922/99991710-63c6e900-2ddb-11eb-9dc9-3420a2df4cbf.png)

**Comment by vipuluthaiah** [comment]
am i  doing it write??

**Comment by vipuluthaiah** [comment]
![AQ](https://user-images.githubusercontent.com/45168922/99991817-86590200-2ddb-11eb-9843-f7e4c1fcdbf3.png)
i am passing this url..also i only pushed only two json data to firestore ...also i used image link from storage..I added the a=images and used that link in cloud firestore...

**Comment by vipuluthaiah** [comment]
![image](https://user-images.githubusercontent.com/45168922/99992141-f10a3d80-2ddb-11eb-9c96-6e2dd75c7149.png)
what am i missing out???

**Comment by vipuluthaiah** [comment]
Stilll i am not able to load the products

**Comment by thenifemi** [comment]
Please try starting fresh, adding everything one at a time by following the instructions in the repo's readMe.

**Comment by vipuluthaiah** [comment]
sure i will do that

**Comment by vipuluthaiah** [comment]
but u dint say me..which exact url u r saying?
const FIREBASE_STORAGE_BUCKET = 'your_own_firebase_ storage_location_key';
where can i find it???

**Comment by thenifemi** [comment]
The storage bucket where you keep your images in Firebase storage.

**Comment by Mecnunzor** [comment]
> i successfully imported all the json to firebase
> ![image](https://user-images.githubusercontent.com/45168922/99894585-514d9200-2cab-11eb-804c-b04ff91f9c05.png)
> ![image](https://user-images.githubusercontent.com/45168922/99894593-5c082700-2cab-11eb-8022-cb1b98ca0093.png)

I did everything but i couldnt import please help me.

**Comment by agedtech** [comment]
You can try
credentials.dart file

const PLACES_API_KEY = 'Elaf__LIKE_YOUR_API_KEY_ajfl4jlafjjaljl';
const FIREBASE_STORAGE_BUCKET = "your_sorage_bucket.appspot.com";

Next create your cloud_functions and inport.js file, Hit upload foodProducts.json file
##thanks to --thenifemi
